// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Lofanmi/go-switch-hosts/internal/network"
	"github.com/Lofanmi/go-switch-hosts/internal/pcap"
	"github.com/Lofanmi/go-switch-hosts/internal/store"
)

// Injectors from wire.go:

func NewApplication() (*Application, func(), error) {
	parser := store.NewDefaultParser()
	hostsConfigLoader := store.NewConfigLoader(parser)
	pcapHandleManager, cleanup, err := pcap.NewHandleManager()
	if err != nil {
		return nil, nil, err
	}
	contractsNetwork, err := network.NewNetwork(pcapHandleManager)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	hostsStore := store.NewHostsStore(hostsConfigLoader, parser, contractsNetwork)
	application := &Application{
		HostsStore: hostsStore,
		Network:    contractsNetwork,
	}
	return application, func() {
		cleanup()
	}, nil
}
